services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=todolistdb'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=root'
    ports:
      - '5432'
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
